/**
 * Supabase Edge Function: GitHub Deploy
 * Creates/updates a GitHub repository with generated website files
 */

import { serve } from 'https://deno.land/std@0.168.0/http/server.ts';
import { createClient } from 'https://esm.sh/@supabase/supabase-js@2';

const corsHeaders = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type',
};

interface DeployRequest {
  jobId: string;
  websiteId: string;
  userId: string;
  repoName: string;
  files: Array<{ path: string; content: string }>;
}

interface GitHubFile {
  path: string;
  content: string;
}

serve(async (req) => {
  if (req.method === 'OPTIONS') {
    return new Response('ok', { headers: corsHeaders });
  }

  try {
    const { jobId, websiteId, userId, repoName, files } = await req.json() as DeployRequest;

    const supabase = createClient(
      Deno.env.get('SUPABASE_URL') ?? '',
      Deno.env.get('SUPABASE_SERVICE_ROLE_KEY') ?? ''
    );

    // Update job progress
    await supabase
      .from('generation_jobs')
      .update({
        current_step: 'Connecting to GitHub',
        progress_percent: 35,
      })
      .eq('id', jobId);

    // Get user's GitHub token
    const { data: profile, error: profileError } = await supabase
      .from('profiles')
      .select('github_access_token, github_username')
      .eq('id', userId)
      .single();

    if (profileError || !profile?.github_access_token) {
      throw new Error('GitHub not connected. Please connect GitHub in Integrations.');
    }

    const githubToken = profile.github_access_token;
    const githubUsername = profile.github_username;

    // Sanitize repo name
    const sanitizedRepoName = repoName
      .toLowerCase()
      .replace(/[^a-z0-9-]/g, '-')
      .replace(/-+/g, '-')
      .replace(/^-|-$/g, '');

    // Update progress
    await supabase
      .from('generation_jobs')
      .update({
        current_step: 'Creating GitHub repository',
        progress_percent: 40,
      })
      .eq('id', jobId);

    // Check if repo exists
    const repoCheckResponse = await fetch(
      `https://api.github.com/repos/${githubUsername}/${sanitizedRepoName}`,
      {
        headers: {
          'Authorization': `Bearer ${githubToken}`,
          'Accept': 'application/vnd.github.v3+json',
        },
      }
    );

    let repoUrl: string;
    let isNewRepo = false;

    if (repoCheckResponse.status === 404) {
      // Create new repo
      const createResponse = await fetch('https://api.github.com/user/repos', {
        method: 'POST',
        headers: {
          'Authorization': `Bearer ${githubToken}`,
          'Accept': 'application/vnd.github.v3+json',
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({
          name: sanitizedRepoName,
          description: `Website generated by RankForge`,
          private: false,
          auto_init: false,
        }),
      });

      if (!createResponse.ok) {
        const errorText = await createResponse.text();
        throw new Error(`Failed to create GitHub repository: ${errorText}`);
      }

      const repoData = await createResponse.json();
      repoUrl = repoData.html_url;
      isNewRepo = true;
    } else if (repoCheckResponse.ok) {
      const repoData = await repoCheckResponse.json();
      repoUrl = repoData.html_url;
    } else {
      throw new Error('Failed to check GitHub repository');
    }

    // Update progress
    await supabase
      .from('generation_jobs')
      .update({
        current_step: 'Pushing files to GitHub',
        progress_percent: 50,
      })
      .eq('id', jobId);

    // For new repos, we need to create the initial commit with all files
    // For existing repos, we update files
    if (isNewRepo) {
      // Create all files in a single commit using the Git Data API
      await createCommitWithFiles(
        githubToken,
        githubUsername,
        sanitizedRepoName,
        files,
        'Initial commit - Website generated by RankForge'
      );
    } else {
      // Update existing repo - get current commit SHA and create new commit
      await updateRepoWithFiles(
        githubToken,
        githubUsername,
        sanitizedRepoName,
        files,
        'Update website - Regenerated by RankForge'
      );
    }

    // Update progress
    await supabase
      .from('generation_jobs')
      .update({
        current_step: 'GitHub deployment complete',
        progress_percent: 60,
      })
      .eq('id', jobId);

    // Update website with repo URL
    await supabase
      .from('websites')
      .update({
        github_repo_url: repoUrl,
      })
      .eq('id', websiteId);

    return new Response(
      JSON.stringify({
        success: true,
        repoUrl,
        repoName: sanitizedRepoName,
        owner: githubUsername,
        isNewRepo,
      }),
      { headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
    );

  } catch (err) {
    console.error('GitHub deploy error:', err);
    return new Response(
      JSON.stringify({ success: false, error: err.message }),
      { status: 500, headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
    );
  }
});

/**
 * Create a new commit with all files using Git Data API
 */
async function createCommitWithFiles(
  token: string,
  owner: string,
  repo: string,
  files: GitHubFile[],
  message: string
): Promise<void> {
  const baseUrl = `https://api.github.com/repos/${owner}/${repo}`;
  const headers = {
    'Authorization': `Bearer ${token}`,
    'Accept': 'application/vnd.github.v3+json',
    'Content-Type': 'application/json',
  };

  // Create blobs for all files
  const blobPromises = files.map(async (file) => {
    const response = await fetch(`${baseUrl}/git/blobs`, {
      method: 'POST',
      headers,
      body: JSON.stringify({
        content: file.content,
        encoding: 'utf-8',
      }),
    });

    if (!response.ok) {
      throw new Error(`Failed to create blob for ${file.path}`);
    }

    const data = await response.json();
    return {
      path: file.path,
      mode: '100644',
      type: 'blob',
      sha: data.sha,
    };
  });

  const treeItems = await Promise.all(blobPromises);

  // Create tree
  const treeResponse = await fetch(`${baseUrl}/git/trees`, {
    method: 'POST',
    headers,
    body: JSON.stringify({
      tree: treeItems,
    }),
  });

  if (!treeResponse.ok) {
    throw new Error('Failed to create tree');
  }

  const treeData = await treeResponse.json();

  // Create commit
  const commitResponse = await fetch(`${baseUrl}/git/commits`, {
    method: 'POST',
    headers,
    body: JSON.stringify({
      message,
      tree: treeData.sha,
    }),
  });

  if (!commitResponse.ok) {
    throw new Error('Failed to create commit');
  }

  const commitData = await commitResponse.json();

  // Create/update main branch reference
  const refResponse = await fetch(`${baseUrl}/git/refs`, {
    method: 'POST',
    headers,
    body: JSON.stringify({
      ref: 'refs/heads/main',
      sha: commitData.sha,
    }),
  });

  if (!refResponse.ok) {
    // Try updating instead
    const updateRefResponse = await fetch(`${baseUrl}/git/refs/heads/main`, {
      method: 'PATCH',
      headers,
      body: JSON.stringify({
        sha: commitData.sha,
        force: true,
      }),
    });

    if (!updateRefResponse.ok) {
      throw new Error('Failed to update branch reference');
    }
  }
}

/**
 * Update existing repo with new files
 */
async function updateRepoWithFiles(
  token: string,
  owner: string,
  repo: string,
  files: GitHubFile[],
  message: string
): Promise<void> {
  const baseUrl = `https://api.github.com/repos/${owner}/${repo}`;
  const headers = {
    'Authorization': `Bearer ${token}`,
    'Accept': 'application/vnd.github.v3+json',
    'Content-Type': 'application/json',
  };

  // Get current commit SHA
  const refResponse = await fetch(`${baseUrl}/git/refs/heads/main`, { headers });

  let parentSha: string | undefined;

  if (refResponse.ok) {
    const refData = await refResponse.json();
    parentSha = refData.object.sha;
  }

  // Create blobs for all files
  const blobPromises = files.map(async (file) => {
    const response = await fetch(`${baseUrl}/git/blobs`, {
      method: 'POST',
      headers,
      body: JSON.stringify({
        content: file.content,
        encoding: 'utf-8',
      }),
    });

    if (!response.ok) {
      throw new Error(`Failed to create blob for ${file.path}`);
    }

    const data = await response.json();
    return {
      path: file.path,
      mode: '100644' as const,
      type: 'blob' as const,
      sha: data.sha,
    };
  });

  const treeItems = await Promise.all(blobPromises);

  // Create tree (with base tree if exists)
  const treeBody: any = { tree: treeItems };
  if (parentSha) {
    // Get parent tree
    const parentCommitResponse = await fetch(`${baseUrl}/git/commits/${parentSha}`, { headers });
    if (parentCommitResponse.ok) {
      const parentCommit = await parentCommitResponse.json();
      treeBody.base_tree = parentCommit.tree.sha;
    }
  }

  const treeResponse = await fetch(`${baseUrl}/git/trees`, {
    method: 'POST',
    headers,
    body: JSON.stringify(treeBody),
  });

  if (!treeResponse.ok) {
    throw new Error('Failed to create tree');
  }

  const treeData = await treeResponse.json();

  // Create commit
  const commitBody: any = {
    message,
    tree: treeData.sha,
  };
  if (parentSha) {
    commitBody.parents = [parentSha];
  }

  const commitResponse = await fetch(`${baseUrl}/git/commits`, {
    method: 'POST',
    headers,
    body: JSON.stringify(commitBody),
  });

  if (!commitResponse.ok) {
    throw new Error('Failed to create commit');
  }

  const commitData = await commitResponse.json();

  // Update branch reference
  if (parentSha) {
    const updateRefResponse = await fetch(`${baseUrl}/git/refs/heads/main`, {
      method: 'PATCH',
      headers,
      body: JSON.stringify({
        sha: commitData.sha,
      }),
    });

    if (!updateRefResponse.ok) {
      throw new Error('Failed to update branch reference');
    }
  } else {
    // Create new branch
    const createRefResponse = await fetch(`${baseUrl}/git/refs`, {
      method: 'POST',
      headers,
      body: JSON.stringify({
        ref: 'refs/heads/main',
        sha: commitData.sha,
      }),
    });

    if (!createRefResponse.ok) {
      throw new Error('Failed to create branch reference');
    }
  }
}
