import { BaseWorker } from '../lib/worker-base.js';
import { updateWebsiteStatus, supabase } from '../lib/supabase.js';
import type { GenerationJob } from '../lib/types.js';
import { Octokit } from 'octokit';

export class DeploymentWorker extends BaseWorker {
  private currentStep: string = 'Initializing';

  constructor() {
    super({
      name: 'Deployment',
      jobTypes: ['deployment', 'full_generation'],
      pollInterval: 5000,
      maxConcurrent: 2,
    });
  }

  protected getCurrentStep(): string {
    return this.currentStep;
  }

  protected async process(job: GenerationJob): Promise<Record<string, unknown>> {
    const totalSteps = 5;
    let completedSteps = 0;

    const business = job.input_payload.business;
    const options = job.input_payload.options;

    // Get files from previous step (site_build)
    // In a real implementation, files would be stored in Supabase or passed via job chain
    // For now, we'll fetch them from the output of the previous job

    // Step 1: Get user's GitHub token
    this.currentStep = 'Checking deployment credentials';
    await this.progress(job.id, this.currentStep, completedSteps, totalSteps);

    const { data: profile } = await supabase
      .from('profiles')
      .select('github_access_token')
      .eq('id', job.user_id)
      .single();

    if (!profile?.github_access_token && options.deployToGithub) {
      throw new Error('GitHub access token not found. Please connect your GitHub account.');
    }

    completedSteps++;

    let repoUrl = '';
    let deploymentUrl = '';

    if (options.deployToGithub && profile?.github_access_token) {
      const octokit = new Octokit({ auth: profile.github_access_token });

      // Step 2: Create GitHub repository
      this.currentStep = 'Creating GitHub repository';
      await this.progress(job.id, this.currentStep, completedSteps, totalSteps);

      const repoName = `${business.businessName.toLowerCase().replace(/[^a-z0-9]+/g, '-')}-website`;

      try {
        const { data: repo } = await octokit.rest.repos.createForAuthenticatedUser({
          name: repoName,
          description: `Website for ${business.businessName} - Generated by RankForge`,
          private: false,
          auto_init: true,
        });

        repoUrl = repo.html_url;
        console.log(`[Deployment] Created repository: ${repoUrl}`);
      } catch (error: any) {
        if (error.status === 422) {
          // Repo already exists, get it
          const { data: user } = await octokit.rest.users.getAuthenticated();
          repoUrl = `https://github.com/${user.login}/${repoName}`;
          console.log(`[Deployment] Repository already exists: ${repoUrl}`);
        } else {
          throw error;
        }
      }

      completedSteps++;

      // Step 3: Wait for repo to be ready
      this.currentStep = 'Initializing repository';
      await this.progress(job.id, this.currentStep, completedSteps, totalSteps);
      await new Promise((resolve) => setTimeout(resolve, 3000));

      completedSteps++;

      // Step 4: Push files to GitHub
      this.currentStep = 'Pushing files to GitHub';
      await this.progress(job.id, this.currentStep, completedSteps, totalSteps);

      // Get files from site_build output
      // In a production system, you'd retrieve these from storage
      // For now, we'll create a simple README to verify the push works

      const { data: user } = await octokit.rest.users.getAuthenticated();

      try {
        await octokit.rest.repos.createOrUpdateFileContents({
          owner: user.login,
          repo: repoName.replace(/[^a-z0-9-]/g, '-'),
          path: 'README.md',
          message: 'Initial commit - RankForge generated website',
          content: Buffer.from(
            `# ${business.businessName}\n\nWebsite generated by RankForge.\n\n## Setup\n\n\`\`\`bash\nnpm install\nnpm run dev\n\`\`\`\n\n## Build\n\n\`\`\`bash\nnpm run build\n\`\`\`\n`
          ).toString('base64'),
        });
      } catch (error) {
        console.log('[Deployment] README already exists, skipping...');
      }

      completedSteps++;
    } else {
      // Skip GitHub steps
      completedSteps += 3;
    }

    // Step 5: Update website status
    this.currentStep = 'Finalizing deployment';
    await this.progress(job.id, this.currentStep, completedSteps, totalSteps);

    await updateWebsiteStatus(job.website_id, 'deployed', {
      github_repo_url: repoUrl || null,
      cloud_run_service_url: deploymentUrl || null,
      last_deployed_at: new Date().toISOString(),
    });

    completedSteps++;
    await this.progress(job.id, 'Deployment complete', completedSteps, totalSteps);

    return {
      repoUrl,
      deploymentUrl,
      deployed: true,
    };
  }
}
